services:

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/db.sqlite
    volumes:
      - ./data:/app/data
    ports:
      - "5004:3000"

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:latest
    restart: unless-stopped
    ports:
      - "3005:80"
    depends_on:
      - backend