# apps/frontend/nginx.conf
# Nginx внутри frontend-контейнера — отдаёт статику React

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # SPA — все маршруты отдают index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}